# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pylagolog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pylagolog.proto',
  package='pylagolog',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fpylagolog.proto\x12\tpylagolog\"?\n\nModifyRule\x12#\n\x04Type\x18\x01 \x01(\x0e\x32\x15.pylagolog.ModifyType\x12\x0c\n\x04Rule\x18\x02 \x01(\t\"/\n\x06Result\x12%\n\x06Result\x18\x01 \x01(\x0e\x32\x15.pylagolog.ReturnCode\"\x16\n\x05Query\x12\r\n\x05Query\x18\x01 \x01(\t\"\x1d\n\x0bQueryResult\x12\x0e\n\x06Result\x18\x01 \x01(\t*$\n\nReturnCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01*!\n\nModifyType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x32~\n\x07\x44\x61talog\x12\x38\n\x08ModRules\x12\x15.pylagolog.ModifyRule\x1a\x11.pylagolog.Result\"\x00(\x01\x12\x39\n\x07Queries\x12\x10.pylagolog.Query\x1a\x16.pylagolog.QueryResult\"\x00(\x01\x30\x01\x62\x06proto3')
)

_RETURNCODE = _descriptor.EnumDescriptor(
  name='ReturnCode',
  full_name='pylagolog.ReturnCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=199,
  serialized_end=235,
)
_sym_db.RegisterEnumDescriptor(_RETURNCODE)

ReturnCode = enum_type_wrapper.EnumTypeWrapper(_RETURNCODE)
_MODIFYTYPE = _descriptor.EnumDescriptor(
  name='ModifyType',
  full_name='pylagolog.ModifyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=237,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_MODIFYTYPE)

ModifyType = enum_type_wrapper.EnumTypeWrapper(_MODIFYTYPE)
SUCCESS = 0
ERROR = 1
ADD = 0
DELETE = 1



_MODIFYRULE = _descriptor.Descriptor(
  name='ModifyRule',
  full_name='pylagolog.ModifyRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='pylagolog.ModifyRule.Type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Rule', full_name='pylagolog.ModifyRule.Rule', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=93,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='pylagolog.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Result', full_name='pylagolog.Result.Result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=142,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='pylagolog.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Query', full_name='pylagolog.Query.Query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=166,
)


_QUERYRESULT = _descriptor.Descriptor(
  name='QueryResult',
  full_name='pylagolog.QueryResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Result', full_name='pylagolog.QueryResult.Result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=197,
)

_MODIFYRULE.fields_by_name['Type'].enum_type = _MODIFYTYPE
_RESULT.fields_by_name['Result'].enum_type = _RETURNCODE
DESCRIPTOR.message_types_by_name['ModifyRule'] = _MODIFYRULE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['QueryResult'] = _QUERYRESULT
DESCRIPTOR.enum_types_by_name['ReturnCode'] = _RETURNCODE
DESCRIPTOR.enum_types_by_name['ModifyType'] = _MODIFYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModifyRule = _reflection.GeneratedProtocolMessageType('ModifyRule', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYRULE,
  __module__ = 'pylagolog_pb2'
  # @@protoc_insertion_point(class_scope:pylagolog.ModifyRule)
  ))
_sym_db.RegisterMessage(ModifyRule)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'pylagolog_pb2'
  # @@protoc_insertion_point(class_scope:pylagolog.Result)
  ))
_sym_db.RegisterMessage(Result)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), dict(
  DESCRIPTOR = _QUERY,
  __module__ = 'pylagolog_pb2'
  # @@protoc_insertion_point(class_scope:pylagolog.Query)
  ))
_sym_db.RegisterMessage(Query)

QueryResult = _reflection.GeneratedProtocolMessageType('QueryResult', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESULT,
  __module__ = 'pylagolog_pb2'
  # @@protoc_insertion_point(class_scope:pylagolog.QueryResult)
  ))
_sym_db.RegisterMessage(QueryResult)



_DATALOG = _descriptor.ServiceDescriptor(
  name='Datalog',
  full_name='pylagolog.Datalog',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=272,
  serialized_end=398,
  methods=[
  _descriptor.MethodDescriptor(
    name='ModRules',
    full_name='pylagolog.Datalog.ModRules',
    index=0,
    containing_service=None,
    input_type=_MODIFYRULE,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Queries',
    full_name='pylagolog.Datalog.Queries',
    index=1,
    containing_service=None,
    input_type=_QUERY,
    output_type=_QUERYRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATALOG)

DESCRIPTOR.services_by_name['Datalog'] = _DATALOG

# @@protoc_insertion_point(module_scope)
